import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

const translations: Record<Language, Record<string, string>> = {
  en: {
    siteName: 'MP Sugam Parivahan',
    siteTitle: 'मुख्यमंत्री सुगम परिवहन सेवा',
    siteSubtitle: 'Madhya Pradesh Government Bus Services',
    home: 'Home',
    routes: 'Routes',
    busStops: 'Bus Stops',
    liveTracking: 'Live Tracking',
    fares: 'Fares',
    cities: 'Cities',
    announcements: 'Announcements',
    planTrip: 'Plan Trip',
    searchBuses: 'Search Buses',
    from: 'From',
    to: 'To',
    date: 'Date',
    selectCity: 'Select City',
    selectDate: 'Select Date',
    popularRoutes: 'Popular Routes',
    serviceStats: 'Service Statistics',
    regionalNetwork: 'MP Regional Bus Network',
    popularDestinations: 'Popular Destinations',
    safetyTech: 'Safety & Technology',
    latestNews: 'Latest Announcements',
    viewRoutes: 'View Routes',
    viewOnMap: 'View on Map',
    shareRoute: 'Share Route',
    saveRoute: 'Save Route',
    demoData: 'Demo Data — Not an official timetable',
    demoTimetable: 'Demo timetable',
    fareNotPublished: 'Fare not yet published',
    timingSubject: 'Timing subject to official schedule',
    timetableUpdating: 'Timetable data is being updated. Please verify before travel.',
    liveUnavailable: 'Live tracking data is currently unavailable.',
    demoMode: 'DEMO MODE',
    noBusesFound: 'No buses found for this search.',
    tryAnother: 'Try another date or destination.',
    searchBusStop: 'Search bus stop',
    calculateFare: 'Calculate Fare',
    fareUnavailable: 'Official fare information is currently unavailable.',
    disclaimer: 'This website is an independent information interface and is not an official government website unless explicitly stated. Timings, fares and availability should be verified from official sources before travel.',
    launchNotice: 'Service information is being updated following the September 25, 2026 launch. Some routes, timings, fares and stop information may not yet be published or may change. Please verify the latest schedule before travelling.',
    initialBuses: 'Initial buses',
    busesAllocated: 'Buses allocated to Indore',
    intracityBuses: 'Intracity buses in Indore',
    intercityBuses: 'Intercity buses in Indore',
    regionalDivisions: 'Regional transport divisions',
    targetFleet: 'Target fleet by 2031',
    launchInfo: 'Launch information',
    busType: 'Bus Type',
    departure: 'Departure',
    arrival: 'Arrival',
    duration: 'Duration',
    distance: 'Distance',
    pickupPoint: 'Pickup Point',
    dropPoint: 'Drop Point',
    facilities: 'Facilities',
    amenities: 'Amenities',
    filter: 'Filter',
    sort: 'Sort',
    ac: 'AC',
    nonAc: 'Non-AC',
    electric: 'Electric',
    cng: 'CNG',
    intracity: 'Intracity',
    intercity: 'Intercity',
    direct: 'Direct',
    fastest: 'Fastest',
    cheapest: 'Cheapest',
    more: 'More',
    live: 'Live',
    search: 'Search',
    onTime: 'On Time',
    delayed: 'Delayed',
    notAvailable: 'Not Available',
    readMore: 'Read More',
    source: 'Source',
    important: 'Important',
    busServices: 'Bus Services',
    majorStops: 'Major Bus Stops',
    totalBuses: 'Total Buses',
    travelAcross: 'Travel Across Madhya Pradesh with Sugam Parivahan',
    hindiSub: 'मध्य प्रदेश में आसान, सुरक्षित और सुगम बस यात्रा',
    searchDesc: 'Search routes, timings, pickup points and bus information across Madhya Pradesh.',
    indoreBusNetwork: 'Indore Bus Network',
    quickLinks: 'Quick Links',
    passengerInfo: 'Passenger Information',
    safety: 'Safety',
    accessibility: 'Accessibility',
    help: 'Help',
    gpsTracking: 'GPS Tracking',
    cctv: 'CCTV Surveillance',
    emergencyButton: 'Emergency Panic Button',
    accessibleBuses: 'Accessible for All',
    gpsDesc: 'Real-time bus tracking across all routes',
    cctvDesc: '24/7 video surveillance for passenger safety',
    emergencyDesc: 'One-touch emergency alert system',
    accessibleDesc: 'Low-floor buses with wheelchair accessibility',
    travelPlanner: 'Travel Planner',
    travelPlannerDesc: 'Plan your journey with smart route recommendations',
    planNow: 'Plan Now',
    busDetails: 'Bus Details',
    operator: 'Operator',
    route: 'Route',
    gpsStatus: 'GPS Status',
    active: 'Active',
    available: 'Available',
    unavailable: 'Unavailable',
    fare: 'Fare',
    routesFound: 'routes found',
    firstDeparture: 'First Departure',
    lastDeparture: 'Last Departure',
    frequency: 'Frequency',
    intermediateStops: 'Intermediate Stops',
  },
  hi: {
    siteName: 'एमपी सुगम परिवहन',
    siteTitle: 'मुख्यमंत्री सुगम परिवहन सेवा',
    siteSubtitle: 'मध्य प्रदेश सरकार बस सेवाएं',
    home: 'होम',
    routes: 'मार्ग',
    busStops: 'बस स्टॉप',
    liveTracking: 'लाइव ट्रैकिंग',
    fares: 'किराया',
    cities: 'शहर',
    announcements: 'घोषणाएं',
    planTrip: 'यात्रा योजना',
    searchBuses: 'बस खोजें',
    from: 'कहां से',
    to: 'कहां तक',
    date: 'तारीख',
    selectCity: 'शहर चुनें',
    selectDate: 'तारीख चुनें',
    popularRoutes: 'लोकप्रिय मार्ग',
    serviceStats: 'सेवा आंकड़े',
    regionalNetwork: 'एमपी क्षेत्रीय बस नेटवर्क',
    popularDestinations: 'लोकप्रिय गंतव्य',
    safetyTech: 'सुरक्षा और प्रौद्योगिकी',
    latestNews: 'नवीनतम घोषणाएं',
    viewRoutes: 'मार्ग देखें',
    viewOnMap: 'नक्शे पर देखें',
    shareRoute: 'मार्ग साझा करें',
    saveRoute: 'मार्ग सहेजें',
    demoData: 'डेमो डेटा — आधिकारिक समय-सारणी नहीं',
    demoTimetable: 'डेमो समय-सारणी',
    fareNotPublished: 'किराया अभी प्रकाशित नहीं',
    timingSubject: 'समय आधिकारिक अनुसूची के अधीन',
    timetableUpdating: 'समय-सारणी डेटा अपडेट हो रहा है। कृपया यात्रा से पहले सत्यापित करें।',
    liveUnavailable: 'लाइव ट्रैकिंग डेटा वर्तमान में उपलब्ध नहीं है।',
    demoMode: 'डेमो मोड',
    noBusesFound: 'इस खोज के लिए कोई बस नहीं मिली।',
    tryAnother: 'कोई अन्य तारीख या गंतव्य आज़माएं।',
    searchBusStop: 'बस स्टॉप खोजें',
    calculateFare: 'किराया गणना करें',
    fareUnavailable: 'आधिकारिक किराया जानकारी वर्तमान में उपलब्ध नहीं है।',
    disclaimer: 'यह वेबसाइट एक स्वतंत्र सूचना इंटरफ़ेस है और स्पष्ट रूप से उल्लेख नहीं होने तक आधिकारिक सरकारी वेबसाइट नहीं है। यात्रा से पहले समय, किराए और उपलब्धता की आधिकारिक स्रोतों से पुष्टि करें।',
    launchNotice: '25 सितंबर 2026 के शुभारंभ के बाद सेवा जानकारी अपडेट की जा रही है। कुछ मार्ग, समय, किराए और स्टॉप जानकारी अभी प्रकाशित नहीं हुई होगी या बदल सकती है। कृपया यात्रा से पहले नवीनतम अनुसूची सत्यापित करें।',
    initialBuses: 'प्रारंभिक बसें',
    busesAllocated: 'इंदौर को आवंटित बसें',
    intracityBuses: 'इंदौर में अंतःनगरीय बसें',
    intercityBuses: 'इंदौर में अंतर्राज्यीय बसें',
    regionalDivisions: 'क्षेत्रीय परिवहन प्रभाग',
    targetFleet: '2031 तक लक्षित बेड़ा',
    launchInfo: 'शुभारंभ जानकारी',
    busType: 'बस प्रकार',
    departure: 'प्रस्थान',
    arrival: 'आगमन',
    duration: 'अवधि',
    distance: 'दूरी',
    pickupPoint: 'पिकअप बिंदु',
    dropPoint: 'ड्रॉप बिंदु',
    facilities: 'सुविधाएं',
    amenities: 'सुविधाएं',
    filter: 'फ़िल्टर',
    sort: 'क्रम',
    ac: 'एसी',
    nonAc: 'नॉन-एसी',
    electric: 'इलेक्ट्रिक',
    cng: 'CNG',
    intracity: 'अंतःनगरीय',
    intercity: 'अंतर्राज्यीय',
    direct: 'सीधा',
    fastest: 'सबसे तेज़',
    cheapest: 'सबसे सस्ता',
    more: 'और',
    live: 'लाइव',
    search: 'खोजें',
    onTime: 'समय पर',
    delayed: 'विलंबित',
    notAvailable: 'उपलब्ध नहीं',
    readMore: 'और पढ़ें',
    source: 'स्रोत',
    important: 'महत्वपूर्ण',
    busServices: 'बस सेवाएं',
    majorStops: 'प्रमुख बस स्टॉप',
    totalBuses: 'कुल बसें',
    travelAcross: 'सुगम परिवहन के साथ मध्य प्रदेश में यात्रा करें',
    hindiSub: 'मध्य प्रदेश में आसान, सुरक्षित और सुगम बस यात्रा',
    searchDesc: 'मध्य प्रदेश भर में मार्ग, समय, पिकअप बिंदु और बस जानकारी खोजें।',
    indoreBusNetwork: 'इंदौर बस नेटवर्क',
    quickLinks: 'त्वरित लिंक',
    passengerInfo: 'यात्री जानकारी',
    safety: 'सुरक्षा',
    accessibility: 'सुलभता',
    help: 'सहायता',
    gpsTracking: 'GPS ट्रैकिंग',
    cctv: 'CCTV निगरानी',
    emergencyButton: 'आपातकालीन बटन',
    accessibleBuses: 'सभी के लिए सुलभ',
    gpsDesc: 'सभी मार्गों पर रीयल-टाइम बस ट्रैकिंग',
    cctvDesc: 'यात्री सुरक्षा के लिए 24/7 वीडियो निगरानी',
    emergencyDesc: 'वन-टच इमरजेंसी अलर्ट सिस्टम',
    accessibleDesc: 'व्हीलचेयर सुलभता के साथ लो-फ्लोर बसें',
    travelPlanner: 'यात्रा योजनाकार',
    travelPlannerDesc: 'स्मार्ट मार्ग अनुशंसाओं के साथ अपनी यात्रा योजना बनाएं',
    planNow: 'अभी योजना बनाएं',
    busDetails: 'बस विवरण',
    operator: 'ऑपरेटर',
    route: 'मार्ग',
    gpsStatus: 'GPS स्थिति',
    active: 'सक्रिय',
    available: 'उपलब्ध',
    unavailable: 'अनुपलब्ध',
    fare: 'किराया',
    routesFound: 'मार्ग मिले',
    firstDeparture: 'पहला प्रस्थान',
    lastDeparture: 'अंतिम प्रस्थान',
    frequency: 'आवृत्ति',
    intermediateStops: 'मध्यवर्ती स्टॉप',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
